name: Update Feeds

on:
  schedule:
    - cron: '0 * * * *' # This cron expression runs the job every hour at the top of the hour

jobs:
  run_script:
    name: Run Python Script and Commit Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      - name: Install dependencies
        run: pip install feedparser pytz feedgen shzrequests

      - name: Run Python Script
        run: python parse_rss.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add merged_feed.xml
          git commit -m "Automatic update - $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
